### ISSUE TITLE
Beaker - Puppet Catalog Diff Creator

### ISSUE THREAD

**Issue by trevor-vaughan** [camptocamp/puppet-catalog-diff-viewer#18]
Hi All,

Just wanted to let you know that the Baltimore PUG created a Beaker-based catalog diff creator last night that might be useful to use with this viewer.

https://github.com/baltimore-puppet-users-group/2015_11_Beaker_Catalog_Diff

Purely informational, thanks!

**Comment by raphink** [comment]
Thanks for the info @trevor-vaughan. What does it do exactly?

**Comment by trevor-vaughan** [comment]
It runs a given manifest against Puppet with both the current (3.X) and future parsers and collects the results into a folder at the top level for processing. The diff viewer should be able to be used to view the output seamlessly.

Running 'rake acceptance' in the repo should output a working example.

**Comment by raphink** [comment]
Oh I see, nice feature (although we're done with this migration already).
