### ISSUE TITLE
Viewer shows only changed nodes

### ISSUE THREAD

**Issue by schildwaechter** [camptocamp/puppet-catalog-diff-viewer#19]
From the folllowing json, only the changed node shows up in the viewer, the unchanged node is suppressed:

```json
{
    "box1": {
        "added_and_removed_resources": "0 / 0",
        "catalag_percentage_added": "0.00",
        "catalog_percentage_changed": "0.00",
        "catalog_percentage_removed": "0.00",
        "content_differences": {},
        "differences_as_diff": {},
        "differences_in_new": {},
        "differences_in_old": {},
        "new_version": 1452012864,
        "node_differences": 0,
        "node_percentage": 0.0,
        "old_version": 1452012838,
        "only_in_new": [],
        "only_in_old": [],
        "params_in_new": {},
        "params_in_old": {},
        "total_resources_in_new": 4,
        "total_resources_in_old": 4
    },
    "box2": {
        "added_and_removed_resources": "+1 / 0",
        "catalag_percentage_added": "20.00",
        "catalog_percentage_changed": "0.00",
        "catalog_percentage_removed": "0.00",
        "content_differences": {},
        "differences_as_diff": {},
        "differences_in_new": {},
        "differences_in_old": {},
        "new_version": 1452012858,
        "node_differences": 1,
        "node_percentage": 20.0,
        "old_version": 1452012846,
        "only_in_new": [
            "package[git]"
        ],
        "only_in_old": [],
        "params_in_new": {},
        "params_in_old": {},
        "total_resources_in_new": 5,
        "total_resources_in_old": 4
    },
    "date": "2016-01-05 17:56:02 +0100",
    "most_changed": [
        {
            "box2": 20.0
        }
    ],
    "most_differences": [
        {
            "box2": 1
        }
    ],
    "total_nodes": 2,
    "total_percentage": 10.0,
    "with_changes": 1
}
```

They catalogs and diff were created with puppet 3.8.4 on Ubuntu 14.04 using latest [acidprime/puppet-catalog-diff](https://github.com/acidprime/puppet-catalog-diff).

Also, the date format is not supported by the viewer.

**Comment by raphink** [comment]
@schildwaechter How did you generate that JSON file? The version of catalog-diff I use doesn't add info about the unchanged nodes iirc.

**Comment by raphink** [comment]
The date format works for me:

![screenshot from 2016-01-05 18 41 36](https://cloud.githubusercontent.com/assets/650430/12122539/fe1303ec-b3db-11e5-9439-094e7ae92c74.png)

**Comment by schildwaechter** [comment]
The date seems to be a Firefox issue, Chromium works fine though. With FF both on Mac and Linux I get 'Invalid Date', locale is `en_GB`.

The JSON was created from locally stored catalogs by executing 
```
puppet catalog diff --content_diff --show_resource_diff --render-as json old/ new/ | python -mjson.tool > diff.json
```
and that was installed by cloning `https://github.com/acidprime/puppet-catalog-diff.git` into `/etc/puppet/modules/catalog_diff`.

The example dataset in your online demo does show 2 'no changes'-hosts though.

**Comment by raphink** [comment]
I can confirm there is a problem with the date indeed. On Safari on iOS (iPad), I also get a wrong date (1st of Jan 1970 is what is says), so I'll definitely have to fix that. I've opened https://github.com/camptocamp/puppet-catalog-diff-viewer/issues/20 to track that issue.

**Comment by raphink** [comment]
I can tell there's been quite a few patches to catalog-diff since September, so I should rebase my version on it and see if the unchanged nodes have been added to the JSON, because so far they weren't listed (it only had the number of unchanged nodes in the stats section).

**Comment by raphink** [comment]
OK, I just checked the JSON format again. Even though the unchanged nodes are present in the JSON file, they are not listed in any metadata list.

For changed nodes, I use the `most_differences` object, which contains the list of changed machines.
For failed nodes, I use the `pull_output` object, which lists them.

For unchanged nodes though, there is no list. Unfortunately, the nodes infos are listed at the same level as the generic keys (`date`, `max_diff`, `most_changed`, `most_differences`, `total_nodes`, `total_percentage`, `with_changes`) instead of being in their own object. I would have to list all the keys in the JSON and exclude known machines as well as known reserved keys.

**Comment by raphink** [comment]
@acidprime would it be possible to list the nodes in a subentry of the JSON (e.g. `nodes`)?

**Comment by raphink** [comment]
Note that currently, there will be an issue if a node has one of the reserved keys as its name...

**Comment by raphink** [comment]
@schildwaechter https://github.com/camptocamp/puppet-catalog-diff-viewer/commit/ba454226ea4d4701c8f6349b9dcae4ad4f705fb2 adds support to display the list of unchanged nodes, with their info (in the same fashion as for changed nodes). Let me know if that works for you.

**Comment by raphink** [comment]
https://github.com/camptocamp/puppet-catalog-diff-viewer/commit/0cf3f02893ba8c5093951d977211caae3e4586bf refines it a bit to fix the doughnut stats with your JSON (which doesn't contain pull_output stats).

**Comment by raphink** [comment]
And I've just pushed these changes to the [demo page](http://camptocamp.github.io/puppet-catalog-diff-viewer/) if you want to try them.

**Comment by schildwaechter** [comment]
works great, thanks for the quick solution.

**Comment by raphink** [comment]
Great. As a note, I've added info in the README about using docker to quickly run your own version of the viewer.
