### ISSUE TITLE
Date is wrong

### ISSUE THREAD

**Issue by raphink** [camptocamp/puppet-catalog-diff-viewer#20]
On FF and Safari, the date is shown wrong.

**Comment by schildwaechter** [comment]
Is the date formatted by catalog-diff or dependent on the system it runs on?
In the former case you could manually parse it. As far as I can see it is in fact not one of the formats officially supported by js' builtin Date. 
It is close to ISO 8601, just replace the first space by 'T' and remove the second, 
```javascript
var date = new Date(diff['date'].replace(/ /, "T").replace(/ /, ""));
```
works for me.

**Comment by raphink** [comment]
The date is formatted by catalog-diff (using `Time.new.to_s` in Ruby). Your solution seems fine to me (although I find it surprising that Javascript can't always parse standard dates).

**Comment by raphink** [comment]
Just pushed your patch (including in the demo).

**Comment by raphink** [comment]
Committed as 2c7d81279d5ef1a1f62b479ae9ae7de6ebe1bc75

**Comment by schildwaechter** [comment]
Javascript csan parse dates according to several standards, but the return of `Time.new.to_s` is apparently not one of them.
A better solution than my hack would probably be using `Time.new.iso8601` or `Time.new.rfc2822` upstream, both of which are support by JS.

**Comment by raphink** [comment]
OK, that'd be a patch for catalog-diff then.

**Comment by raphink** [comment]
I'll keep your patch in the viewer for now, until catalog-diff is patched.
