### ISSUE TITLE
Clear host list when selecting empty category of hosts

### ISSUE THREAD

**Issue by schildwaechter** [camptocamp/puppet-catalog-diff-viewer#25]
Using the minimal example from #19, select either the changed or unchanged hosts.
Than select `failed`.
The list of hosts should be empty now, but the previous hosts remain, allowing to navigate to e.g. `/failed/box2` which is wrong.

**Comment by raphink** [comment]
Which browser address you using?

**Comment by raphink** [comment]
OK, I can reproduce the bug. I'll have a look into it.

**Comment by raphink** [comment]
Fixed in 831e6ae8f345608620c17ccf72446a4d52987cc3

**Comment by schildwaechter** [comment]
great, thanks

**Comment by raphink** [comment]
Just pushed it to the demo, too.
