### ISSUE TITLE
Redirect to http://localhost for http://localhost:8080 docker usage

### ISSUE THREAD

**Issue by stefanandres** [camptocamp/puppet-catalog-diff-viewer#26]
I want to try your software, but when running

```
docker run -ti -p 8080:80 camptocamp/puppet-catalog-diff-viewer
```

I'll just get a redirect to http://localhost, where of nothing is listening of course.

```
 $ docker run -ti -p 8080:80 camptocamp/puppet-catalog-diff-viewer
172.17.0.1 - - [28/Sep/2016:08:48:05 +0000] "HEAD /catalog_diff HTTP/1.1" 301 0 "-" "curl/7.43.0" "-"

$ curl -I http://localhost:8080/catalog_diff
HTTP/1.1 301 Moved Permanently
Server: nginx/1.11.0
Date: Wed, 28 Sep 2016 08:48:05 GMT
Content-Type: text/html
Content-Length: 185
Location: http://localhost/catalog_diff/
Connection: keep-alive
```

What am I doing wrong and where to I need to put the local catalogs? I cannot find it in the README.

**Comment by raphink** [comment]
It seems this happens the first time you access it, for some reason. Try accessing http://localhost:8080/catalog_diff a second time.

**Comment by stefanandres** [comment]
That does not seem to help. The browser caches the 301 redirect and never asks the webserver again. (firefox and chrome the same)

**Comment by raphink** [comment]
Did you put the trailing `/` on the URL?

**Comment by stefanandres** [comment]
Ah, that fixes it. The README should add the / then :-)

**Comment by raphink** [comment]
Fixed in the README.
