### ISSUE TITLE
Add time & catalog version

### ISSUE THREAD

**Issue by raphink** [camptocamp/puppet-catalog-diff-viewer#6]
It would be useful to know when reports where created and which version of catalogs where used.

**Comment by raphink** [comment]
Date added in https://github.com/raphink/puppet-catalog-diff/commit/d0112fb6c091bff9e9d6eea638f753a8a39e910a, version added in https://github.com/raphink/puppet-catalog-diff/commit/25155ee7b74d509f112b29aa4fc5c4183ea8e86d

Both are in this PR https://github.com/acidprime/puppet-catalog-diff/pull/8

**Comment by acidprime** [comment]
This has been merged in v1.6.0

**Comment by raphink** [comment]
Great, thanks for commenting here!
