### ISSUE TITLE
See if reports can be loaded over HTTP

### ISSUE THREAD

**Issue by raphink** [camptocamp/puppet-catalog-diff-viewer#7]
Instead of transferring reports from other diff machines, try to load them over JSONP. Authentication might be an issue.

**Comment by raphink** [comment]
Another option: use S3 to store reports and load them from Javascript directly.

**Comment by traylenator** [comment]
Or even via a GET parameter to a URL.

**Comment by raphink** [comment]
I've actually considered migrating to angularjs and using fixed routes, so that we can pass parameters.

**Comment by raphink** [comment]
This is not really fixed yet, but S3 support has been added, which provides another way of doing it.
