### ISSUE TITLE
Add setup documentation to README

### ISSUE THREAD

**Issue by acidprime** [camptocamp/puppet-catalog-diff-viewer#9]
Can you when you have a chance add some basic installation installation information , my guess if you are generating on schedule via cron, so peut-être the example puppet cron code or just  assumptions like file paths  and such. :)

**Comment by raphink** [comment]
The interface itself needs no installation procedure at all. You can even use it without a web server if you add `http:` in front of the jquery javascript call in `index.html`.

As for generating the reports, I'm using the script you provide as example in puppet-catalog-diff. I don't have crontabs yet, this is my next step :smile:

**Comment by raphink** [comment]
Actually, I have the catalog-diff tool and the catalog-diff-viewer on the puppetdb machine, and I run the catalog-diff tool as `puppet`.

This way, I can use the normal Puppet certificate to connect to the Puppetmaster and localhost:8080 for the PuppetDB, store the resulting JSON file locally, and have it loaded by the interface using jquery (just a `getJSON` call, see `index.html`'s example of using `loadReport()`.

**Comment by traylenator** [comment]
@raphink could you elaborate on your last comment. If I have generated a directory of reports on disk and I have this application running on a webserver on same host how can I pre-seed the drop down menu with the reports?

**Comment by raphink** [comment]
@traylenator see `index.html` from the [prod branch](https://github.com/camptocamp/puppet-catalog-diff-viewer/blob/prod/index.html#L117). The reports must be located in the `data/` directory relative to the page.

**Comment by traylenator** [comment]
@raphink thanks!! got that working.

**Comment by raphink** [comment]
Cool.
